---
- name: Calculator MiniProject
  hosts: localhost
  remote_user: tanmay233
  become: false
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "tanmay2233/calculator-miniproject"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result
        
    - name: Start Docker Service
      service:
        name: docker
        state: started

    - name: Running Container
      shell: docker run -it -d --name=calculator tanmay2233/calculator-miniproject